### PR TITLE
Davy edits

### PR DESCRIPTION
**Pull request by davydw**
@zzuziak  
1. I uploaded complete solutions to the two quizzes
2. Fixed some typos

### CODE REVIEW

**Comment by zzuziak** [comment]
@krokrob  we removed the solutions from this repo so that students can't access them, right? :thinking:

**Comment by davydw** [comment]
@krokrob @zzuziak  then we could create a repo data-quizzes-solution :) ?

**Comment by zzuziak** [comment]
@davydw can you remove solutions from this PR so I can merge the fixes in the empty notebooks?

**Comment by davydw** [comment]
@zzuziak  I removed the solutions from this PR :)

**Review by zzuziak — APPROVED** [review]

**Comment by zzuziak** [comment]
:tada:

**Pull request merged**
